### PR TITLE
Update to newer release

### PR DESCRIPTION
**Pull request by simonbyrne**

### CODE REVIEW

**Comment by simonbyrne** [comment]
Hmm, I'm stuck. No idea why this isn't working.

**Comment by simonbyrne** [comment]
@quinnj I think this is ready

**Review by quinnj — APPROVED** [review]
Thanks!

**Comment by simonbyrne** [comment]
There's some sort of credential issue:
https://travis-ci.org/quinnj/DecFPBuilder/jobs/502400950#L649

**Comment by quinnj** [comment]
Ok, got it working: https://github.com/quinnj/DecFPBuilder/releases/tag/v0.7. @simonbyrne, would you mind doing the PR to DecFP.jl?

**Pull request merged**
