### PR TITLE
Updates to Windows build

### PR DESCRIPTION
**Pull request by jmkuhn**
Fix Windows build issues seen in https://github.com/JuliaMath/DecFP.jl/pull/90

### CODE REVIEW

**Comment by jmkuhn** [comment]
I was using https://github.com/JuliaLinearAlgebra/OpenBLASBuilder as an example of how to include and apply a patch file, but I obviously misunderstand how this works.

Edit: needed to add bundled directory to sources array.

**Comment by quinnj** [comment]
Cool, so is this good to go?

**Comment by jmkuhn** [comment]
Good to go.

**Comment by jmkuhn** [comment]
Thanks for the merge and release.  The v0.10 build script has all the expected targets in it but the download/v0.10 directory is missing 4 *.tar.gz files:   i686-linux-musl, i686-linux-gnu, x86_64-apple-darwin, x86_64-linux-gnu

**Comment by quinnj** [comment]
I restarted the travis job here: https://travis-ci.org/quinnj/DecFPBuilder/builds/535827918

**Comment by jmkuhn** [comment]
Thanks. They are all available now.

**Comment by jmkuhn** [comment]
I have everything I need now but I wanted to point this out.  The SHA checksums for the 4 originally missing .tar.gz files are incorrect in the download/v0.10/build_DecFP.v2.2.0.jl file.

**Pull request merged**
